<?php
$paramsRouter = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch()->getParams();
$routeName = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch();
$controller = $paramsRouter['__CONTROLLER__'];
$action = $paramsRouter['action'];
$cateId = (isset($paramsRouter['cateId'])) ? $paramsRouter['cateId'] : '';
//
$arr_category_parent = unserialize(ARR_CATEGORY_PARENT);
?>

<div class="navbox sidenav sticky">
    <ul class="navigation clearfix">
            <li>
                <a href="#">
                    <?php echo 'Menu' ?>
                </a>
                    <ul>
                        <?php foreach ($arr_category_parent as $cate_child): ?>
                            <li class="tax-<?php echo $cate_child['cate_slug'] ?> <?php echo ($cate_child == $cateId) ? 'active' : '' ?>">
                                <a href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $cate_child['cate_slug'], 'cateId' => $cate_child['cate_id']]) ?>">
                                    <img
                                        src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/images/icon/' . $cate_child['cate_icon'] . '.png'; ?>"/>
                                    <?php echo $cate_child['cate_name'] ?>
                                </a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
            </li>
    </ul>
</div>
